alltopicdjango/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from signaltask.views import homee

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dynamicurl/" , include(("dynamicurl.urls" , "dynamicurl") , namespace="dynamicurl")),
    path("form/" , include(("form.urls" , "form") , namespace="form")),
    path("authenticate/" , include(("authenticate.urls" , "authenticate") , namespace="authenticate")),
    path("cookiesession/" , include(("cookiesession.urls" , "cookiesession") , namespace="cookiesession")),
    path("cacheapp/" , include(("cacheapp.urls" , "cacheapp") , namespace="cacheapp")),
    path("customesignal/" , homee ),
    path("middlewarecheck/" , include(("middlewarecheck.urls" , "middlewarecheck") , namespace="middlewarecheck")),
    path("modelchecking/" , include(("modelchecking.urls" , "modelchecking") , namespace="modelchecking")),
    path("modelmanagerconcept/" , include(("modelmanagerconcept.urls" , "modelmanagerconcept") , namespace="modelmanagerconcept")),
    path("modelrelationship/" , include(("modelrelationship.urls" , "modelrelationship") , namespace="modelrelationship")),
    path("classbasedvieww/" , include(("classbasedvieww.urls" , "classbasedvieww") , namespace="classbasedvieww")),
    path("authorizations/" , include(("authorizations.urls" , "authorizations") , namespace="authorizations")),
    path('accounts/' , include('django.contrib.auth.urls')),
    path('accounts/' , include(("authorizations.urls" , "authorizations") , namespace="authorizations"))

]

dynamicurl/urls.py
from django.urls import path,register_converter
from .views import home,profile
from .converter import FourDigitYearConverter
register_converter(FourDigitYearConverter,'yyyy')


urlpatterns = [
    path('' , home , name="home"),
    path("myprofile/<int:id>" , profile , name="profile"),
    path("session/<yyyy:id>/" , profile , name="session")

]

form/urls.py
from django.urls import path,register_converter
from .views import insertuser,insertuserForm


urlpatterns = [
    path('' , insertuser , name="create"),
    path('createform/' , insertuserForm , name="createusingform")
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="container-fluid">
{% block content %}



{% endblock %}
</div>


</body>
</html>

templates/dynamic.html
{% extends 'base.html' %}
{% block  content %}
<h1 style="text-align:center"> Dynamic Urls </h1>
<a style="margin-right:10px" href=""> Home  </a>
<a style="margin-right:10px" href="{% url 'dynamicurl:profile'  1 %}"> Student 1 </a>
<a style="margin-right:10px" href="{% url 'dynamicurl:profile'  2 %}"> Student 2 </a>
<a style="margin-right:10px" href="{% url 'dynamicurl:profile'  3 %}"> Student 3 </a>


<br/><br/><br/><br/>
<a href=""> Go Back Home  </a>

{% endblock  %}